import type { Project } from "./portfolio";

const U = (id: string, w = 900, h = 560) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const projectsId: Project[] = [
  {
    slug: "cukur-express-barbershop",
    title: "Cukur Express — Booking Barbershop",
    category: "Barbershop",
    industry: "Barbershop",
    type: "Website", year: 2025,
    summary: "Website booking barbershop dengan ketersediaan kursi real-time, pengingat WhatsApp, dan kartu stamp loyalitas. Booking online meningkat 3x dalam 2 bulan.",
    client: "Cukur Express", location: "Bandung, Indonesia", duration: "3 minggu",
    stack: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Midtrans", "Twilio"],
    features: [
      "Jadwal per-barber dengan proteksi double-booking",
      "Pengingat SMS + WhatsApp 24 jam dan 1 jam sebelum jadwal",
      "Kartu stamp loyalitas (setiap cukur ke-10 gratis)",
      "Tampilan antrian walk-in untuk TV di barbershop",
      "Dashboard owner: pendapatan harian + tingkat no-show",
    ],
    results: [
      { label: "Booking online", value: "+312%" },
      { label: "Tingkat no-show", value: "-48%" },
      { label: "Waktu booking rata-rata", value: "38 detik" },
    ],
    hero: { from: "#1f1147", to: "#7c5cff", emoji: "💈" },
    photo: U("photo-1503951914875-452162b0f3f1"),
    photos: [U("photo-1503951914875-452162b0f3f1"), U("photo-1599351431202-1e0f0137899a"), U("photo-1621605815971-fbc98d665033")],
  },
  {
    slug: "cantik-salon-kecantikan",
    title: "Cantik.id — Salon Kecantikan",
    category: "Salon Kecantikan",
    industry: "Salon Kecantikan",
    type: "Web App", year: 2025,
    summary: "Platform booking multi-stylist dengan layanan add-on, pembayaran deposit, dan funnel ulasan Google yang melipatduakan jumlah bintang 5 mereka.",
    client: "Cantik.id Studio", location: "Jakarta, Indonesia", duration: "5 minggu",
    stack: ["Next.js", "Prisma", "PostgreSQL", "Midtrans", "Cloudinary"],
    features: [
      "Profil stylist dengan galeri portofolio",
      "Paket layanan + upsell add-on saat checkout",
      "Deposit non-refundable untuk kurangi no-show",
      "Auto-prompt ulasan Google setelah kunjungan",
      "Pelacakan inventaris produk retail",
    ],
    results: [
      { label: "Ulasan Google", value: "+218%" },
      { label: "Rata-rata nilai transaksi", value: "+27%" },
      { label: "Booking berulang", value: "+41%" },
    ],
    hero: { from: "#3a0d3a", to: "#ff7ac6", emoji: "💅" },
    photo: U("photo-1560066984-138dadb4c035"),
    photos: [U("photo-1560066984-138dadb4c035"), U("photo-1522337360788-8b13dee7a37e"), U("photo-1487412947147-5cebf100ffc2")],
  },
  {
    slug: "bersihkilat-laundry",
    title: "BersihKilat — Laundry Kiloan",
    category: "Laundry",
    industry: "Laundry",
    type: "Website", year: 2025,
    summary: "Website laundry dengan booking antar-jemput, tracking status cucian real-time, dan notifikasi WhatsApp otomatis. Pelanggan baru meningkat 4x.",
    client: "BersihKilat Laundry", location: "Surabaya, Indonesia", duration: "3 minggu",
    stack: ["Next.js", "Tailwind", "Supabase", "Twilio", "Midtrans"],
    features: [
      "Booking antar-jemput dengan slot waktu",
      "Tracking status: Dijemput → Dicuci → Siap → Diantar",
      "Notifikasi WhatsApp otomatis setiap perubahan status",
      "Langganan mingguan dengan auto-tagih via Midtrans",
      "Dashboard owner: omzet harian, status cucian aktif",
    ],
    results: [
      { label: "Pelanggan baru/bulan", value: "+4×" },
      { label: "Pelanggan langganan", value: "+67%" },
      { label: "Panggilan telepon berkurang", value: "80%" },
    ],
    hero: { from: "#06283d", to: "#22d3ee", emoji: "🧺" },
    photo: U("photo-1545173168-9f1947eebb7f"),
    photos: [U("photo-1545173168-9f1947eebb7f"), U("photo-1582735689369-4fe89db7114c"), U("photo-1558618047-3c8c76ca7d13")],
  },
  {
    slug: "cooltech-service-ac",
    title: "CoolTech — Service AC & Elektronik",
    category: "Service AC",
    industry: "Service AC",
    type: "Mobile App", year: 2025,
    summary: "Aplikasi iOS + Android untuk panggilan darurat AC. Pelanggan request service, lihat ETA teknisi, dan bayar in-app. Dibangun dengan Expo.",
    client: "CoolTech Service", location: "Tangerang, Indonesia", duration: "8 minggu",
    stack: ["React Native (Expo)", "TypeScript", "Firebase", "Midtrans", "Mapbox"],
    features: [
      "Alur panggilan darurat vs. jadwal servis berkala",
      "ETA teknisi real-time di peta",
      "Upload foto kerusakan sebelum dispatch",
      "Harga bertingkat: biaya panggil + per jam + spare part",
      "Invoice digital + PDF garansi servis",
    ],
    results: [
      { label: "Waktu respons rata-rata", value: "-44%" },
      { label: "Pembayaran tunai → digital", value: "91%" },
      { label: "Ulasan bintang 5", value: "+186%" },
    ],
    hero: { from: "#062840", to: "#38bdf8", emoji: "❄️" },
    photo: U("photo-1504328345606-18bbc8c9d7d1"),
    photos: [U("photo-1504328345606-18bbc8c9d7d1"), U("photo-1621905251189-08b45d6a269e"), U("photo-1558618666-fcd25c85cd64")],
  },
  {
    slug: "motormate-bengkel",
    title: "MotorMate — Bengkel Motor",
    category: "Bengkel Motor",
    industry: "Bengkel Motor",
    type: "Mobile App", year: 2025,
    summary: "Aplikasi servis motor on-demand. Pemilik motor deskripsikan masalah, dapat estimasi instan, dan mekanik datang ke lokasi. Termasuk aplikasi sisi mekanik.",
    client: "MotorMate Auto", location: "Jakarta, Indonesia", duration: "10 minggu",
    stack: ["React Native (Expo)", "Node.js", "PostgreSQL", "Socket.IO", "Midtrans"],
    features: [
      "Wizard diagnostik berbasis gejala untuk estimasi instan",
      "Dispatch real-time ke mekanik terdekat yang tersedia",
      "Chat in-app + foto masalah motor",
      "Sisi mekanik: antrian job, pemesanan spare part, payout harian",
      "Riwayat servis per motor berbasis plat nomor",
    ],
    results: [
      { label: "Job/mekanik/hari", value: "+58%" },
      { label: "Rating pelanggan", value: "4.9★" },
      { label: "ETA dispatch", value: "<22 menit" },
    ],
    hero: { from: "#1a0a00", to: "#fb923c", emoji: "🏍️" },
    photo: U("photo-1558618666-fcd25c85cd64"),
    photos: [U("photo-1558618666-fcd25c85cd64"), U("photo-1530046339160-ce3e530c7d2f"), U("photo-1486262715619-67b85e0b08d3")],
  },
  {
    slug: "dapurkita-catering",
    title: "DapurKita — Catering & Wedding",
    category: "Catering",
    industry: "Catering",
    type: "Web App", year: 2024,
    summary: "Platform booking catering dengan kalkulator harga per porsi, galeri menu, pembayaran DP, dan manajemen jadwal event. Pesanan meningkat 3x dalam sebulan.",
    client: "DapurKita Catering", location: "Yogyakarta, Indonesia", duration: "5 minggu",
    stack: ["Next.js", "Prisma", "PostgreSQL", "Midtrans", "Cloudinary"],
    features: [
      "Kalkulator harga otomatis (jumlah porsi × paket)",
      "Galeri menu dengan foto HD per paket",
      "Pembayaran DP 30% otomatis via Midtrans",
      "Kalender ketersediaan untuk hindari double-booking",
      "Dashboard owner: jadwal event, status pembayaran, kontak klien",
    ],
    results: [
      { label: "Pesanan per bulan", value: "+3×" },
      { label: "Konversi inquiry → bayar", value: "+52%" },
      { label: "Waktu respons estimasi", value: "< 2 menit" },
    ],
    hero: { from: "#2a0a00", to: "#f97316", emoji: "🍱" },
    photo: U("photo-1555244162-803834f70033"),
    photos: [U("photo-1555244162-803834f70033"), U("photo-1414235077428-338989a2e8c0"), U("photo-1547592180-85f173990554")],
  },
  {
    slug: "pindahyuk-jasa-pindahan",
    title: "PindahYuk — Jasa Pindahan",
    category: "Jasa Pindahan",
    industry: "Jasa Pindahan",
    type: "Website", year: 2024,
    summary: "Website booking pindahan dengan kalkulator harga otomatis (jarak + jumlah barang), jadwal real-time, dan pelacakan truk via GPS.",
    client: "PindahYuk Express", location: "Bekasi, Indonesia", duration: "4 minggu",
    stack: ["Next.js", "Tailwind", "Supabase", "Google Maps API", "Twilio"],
    features: [
      "Kalkulator harga instan (kota asal → tujuan + jumlah barang)",
      "Foto inventaris barang sebelum muat",
      "Pelacakan truk real-time via GPS untuk pelanggan",
      "Notifikasi WhatsApp setiap tahap (konfirmasi, berangkat, sampai)",
      "Dashboard dispatcher: jadwal truk, rute, catatan khusus",
    ],
    results: [
      { label: "Konversi kalkulator → booking", value: "3.8×" },
      { label: "Komplain barang hilang/rusak", value: "-92%" },
      { label: "Rating Google Maps", value: "4.8★" },
    ],
    hero: { from: "#0a1520", to: "#6366f1", emoji: "📦" },
    photo: U("photo-1601584115197-04ecc0da31d7"),
    photos: [U("photo-1601584115197-04ecc0da31d7"), U("photo-1416879595882-3373a0480b5b"), U("photo-1600880292203-757bb62b4baf")],
  },
];

export const categoriesId = Array.from(new Set(projectsId.map((p) => p.category)));
